FORMAT: 1A
HOST: http://www.google.com

# Global
Global APIs for Mobile Web

# Group Empty

## Empty [/pages/empty.json]
### Default [GET]
+ Response 200 (application/json)

        {
        }
        
## Empty with menu [/pages/empty/menu.json]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "backButton": {
                    "url": "index.html"
                }
            },
            "iwantto": [
                {
                    "text": "Hacer transferencia",
                    "type": "OPERATION",
                    "url": "transfers.html",
                    "eventId": null,
                    "jsId": null,
                    "params": null
                },
                {
                    "text": "Filtrar movimientos",
                    "type": "SEARCH",
                    "url": null,
                    "eventId": null,
                    "jsId": "js-filter-movements",
                    "params": null
                }
            ]
        }

## Empty with menu without link [/pages/empty/menu-no-back.json]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "hideBackButton": true
            }
        }

        
# Group Language

## Load page [/pages/language.json]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": false,
                "hideBackButton": true
            },
            "pageContent": [
                {
                    "code": "en",
                    "name": "english",
                    "messageKey": "public.language.english",
                    "selected": true
                },
                {
                    "code": "es",
                    "name": "spanish",
                    "messageKey": "public.language.spanish",
                    "selected": false
                }
            ]
        }
        
## Service center page [/pages/language.json?mockId=1]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "backButton": {
                    "url": "index.html"
                }
            }
        }


# Group Index

## English index [/pages/index.json]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "hideBackButton": true
            },
            "pageContent": {
                "feedback": "https://secure.opinionlab.com/ccc01/o.asp?id=CHAfLukV"
            }
        }


## Remembered user [/pages/index.json?mockId=2]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "hideBackButton": true
            },
            "pageContent": {
                "feedback": "https://secure.opinionlab.com/ccc01/o.asp?id=CHAfLukV",
                "remembered": true,
                "nickname": "Marcos Manuel",
                "lastSignonDate": "Wednesday 03/12/2014"
            }                
        }




# Group Find us

## ATM & Branches [/api/findus/pois.json]
### Default [GET]

+ Request

        {
            "latitude": 33.52472222222222,
            "longitude": 86.81277777777778,
            "radius": null,
            "limit": null,
            "startAt": null
        }

+ Response 200 (application/json)

        {
            "alerts": null,
            "pageContent":[
                {
                    "type": "atm",
                    "idPoi": "atm_us_23_atm_us_bbva_atm",
                    "description": "BBVA ATM",
                    "latitude": 40.492765,
                    "longitude": -3.687185799999952,
                    "idBank": "9999",
                    "address1": "801 17th St N",
                    "address2": "Birmingham, AL 35203",
                    "distance": 605.950699987913,
                    "lobbyHours":{
                        "hours_mt":"24 hour - Yes"
                    }
                    
                },
                {
                    "type": "allPoint",
                    "idPoi": "allpoint_us_43_allpoint_us_bbva_allpoint",
                    "description": "All Point",
                    "latitude": 40.486009,
                    "longitude": -3.687052,
                    "idBank": "9999",
                    "address1": "801 17th St N",
                    "address2": "Birmingham, AL 35203",
                    "distance": 605.950699987913
                },
                {
                    "type": "branch",
                    "idPoi": "branch_us_12_branch_us_bbva_branch",
                    "description": "BBVA Branch",
                    "latitude": 40.480757,
                    "longitude": -3.68611,
                    "idBank": "9999",
                    "address1": "505 N 20th St, Suite 100",
                    "address2": "Birmingham, AL 35203",
                    "telephone": "(205) 297-3206",
                    "distance": 843.044010287908,
                    "lobbyHours":{
                        "hours_mt":"24 hour - Yes",
                        "hours_fri":"24 hour - Yes",
                        "hours_sat":"24 hour - No"
                    },
                    "driveHours":{
                        "hours_mt":"12 hour - Yes",
                        "hours_fri":"12 hour - Yes",
                        "hours_sat":null
                    }
                    
                    
                },
                {
                    "type": "branch",
                    "idPoi": "branch_us_22_branch_us_bbva_branch",
                    "description": "BBVA Branch",
                    "latitude": 40.487905,
                    "longitude": -3.694202,
                    "idBank": "9999",
                    "address1": "15 S 20th St",
                    "address2": "Birmingham, AL 35203",
                    "telephone": "(205) 297-1986",
                    "distance": 843.044010287908,
                     "lobbyHours":{
                        "hours_mt":"24 hour - Yes",
                        "hours_fri":"24 hour - Yes",
                        "hours_sat":"24 hour - No"
                    },
                    "driveHours":{
                        "hours_mt":"12 hour - Yes",
                        "hours_fri":"12 hour - Yes",
                        "hours_sat":null
                    }
                }
            ]
            
        }


## Search address [/api/findus/address.json]
### Default [GET]

+ Request

        {
            "address": "Cardenal Herrera Oria"
        }

+ Response 200 (application/json)

        {
            "alerts": null,
            "pageContent": [
                {
                    "latitude": 40.48214,
                    "longitude": -3.718589,
                    "address1": "Avenida Cardenal Herrera Oria, Madrid, España"
                },
                {
                    "latitude": 36.840657,
                    "longitude": -2.455252,
                    "address1": "Calle Cardenal Herrera Oria, Almeria, España"
                },
                {
                    "latitude": 43.455987,
                    "longitude": -3.851849,
                    "address1": "Avenida Cardenal Herrera Oria, Santander, España"
                },
                {
                    "latitude": 43.458694,
                    "longitude": -3.841492,
                    "address1": "Calle Cardenal Herrera Oria, Santander, España"
                },
                {
                    "latitude": 36.428944,
                    "longitude": -5.14776,
                    "address1": "Calle Cardenal Herrera Oria, 29680 Estepona, Málaga, España"
                }
            ]
        }


## Search address with empty result [/api/findus/address.json?mockId=2]
### Default [GET]

+ Request

        {
            "address": "Euclideaaa"
        }

+ Response 200 (application/json)

        {
            "alerts": [
                {
                    "type": "INFO",
                    "alert": [
                        {
                            "text": "No nearby points of interests found of the type.",
                            "field": ""
                        }
                    ]
                }
            ],
            "pageContent": []
        }


# Group Warnings


## Warnings [/pages/warnings.json]
### Default [GET]
+ Response 200 (application/json)

        { 
            "text": "Mobile and Online Banking will be unavailable Sat 11/23 from 12AM to 3AM CT",
            "url":"",
            "active":"N"
        }



# Group Error

Global error view

## Error with custom messages [/pages/error.json]
### Custom error [GET]
+ Response 200 (application/json)

        {
            "error": {
                "errorMsg": "Some error happened while performing operation"
            }
        }

## Error without custom messages [/pages/error.json?mockId=2]
### Custom error [GET]
+ Response 200 (application/json)

        {
            
        }
        

# Group I Want To

I Want To Button example

## I Want To [/components/iwantto.json]
### Custom error [GET]
+ Response 200 (application/json)

        {
            "iwantto": [
                {
                    "text": "Hacer transferencia",
                    "type": "OPERATION",
                    "url": "transfers.html",
                    "eventId": null,
                    "jsId": null,
                    "params": null
                },
                {
                    "text": "Filtrar movimientos",
                    "type": "SEARCH",
                    "url": null,
                    "eventId": null,
                    "jsId": "js-filter-movements",
                    "params": null
                }
            ]
        }


# Group New Features

Example of new features

## Examples of spanish Web [/pages/newFeatures.json]
### Valid response [GET]
+ Response 200 (application/json)

        {
            "pageContent": [
                {
                    "title": "Automatic access",
                    "image": {
                        "alt": "Automatic access",
                        "url": "http://dev-bbva-buzz.appspot.com/dist_0.1.0/images/release/acceso.png"
                    },
                    "text": "Access the application directly without needing to enter your password. Register for the Automatic Access service, which you can access from \"Menu - Settings\" and enter quickly and securely."
                },
                {
                    "title": "\"About\" on side menu",
                    "image": {
                        "alt": "\"About\" on side menu",
                        "url": "http://dev-bbva-buzz.appspot.com/dist_0.1.0/images/release/acceso.png"
                    },
                    "text": "We have created a section for you in which you can view the application's new features, report errors and rate the application, as well as following BBVA breaking news on social networks."
                },
                {
                    "title": "Payment of bills that are not direct debited",
                    "image": {
                        "alt": "Payment of bills that are not direct debited",
                        "url": "http://dev-bbva-buzz.appspot.com/dist_0.1.0/images/release/rnd.png"
                    },
                    "text": "You can now pay your bills and taxes that are not direct debited from your cell phone, by taking a photo of the barcode with your camera. Go to the \"Non-direct debited payments\" on the Menu and select the option that best matches your preferences."
                },        
                {
                    "title": "See card CVV",
                    "image": {
                        "alt": "See card CVV",
                        "url": "http://dev-bbva-buzz.appspot.com/dist_0.1.0/images/release/alta.png"
                    },
                    "text": "Now you can view the CVV of any of your cards from the BBVA mobile application. Click on the image of your card that is displayed at the top."
                },        
                {
                    "title": "Activate card",
                    "image": {
                        "alt": "Activate card",
                        "url": "http://dev-bbva-buzz.appspot.com/dist_0.1.0/images/release/adjuntos.png"
                    },
                    "text": "Use your new cards right away. You can activate them from \"I want\" on the Menu."
                },        
                {
                    "title": "Copy account IBAN number",
                    "image": {
                        "alt": "Copy account IBAN number",
                        "url": "http://dev-bbva-buzz.appspot.com/dist_0.1.0/images/release/rnd.png"
                    },
                    "text": "Share your account number easily. To copy the IBAN, just click on the account icon at the top of the detailed transactions. You can also do it from \"I want - More information\"."
                },        
                {
                    "title": "Copy card PAN",
                    "image": {
                        "alt": "Copy card PAN",
                        "url": "http://dev-bbva-buzz.appspot.com/dist_0.1.0/images/release/adjuntos.png"
                    },
                    "text": "Save time with your Internet purchases by copying your card number (PAN). You will do it from \"I want - More information\" for any of them."
                },        
                {
                    "title": "Repeat transfer",
                    "image": {
                        "alt": "Repeat transfer",
                        "url": "http://dev-bbva-buzz.appspot.com/dist_0.1.0/images/release/acceso.png"
                    },
                    "text": "Access the details about a transfer and you can easily repeat the transaction, with the details already loaded and the option to modify them."
                }
            ]
        }

