FORMAT: 1A
HOST: http://www.google.com

# Global
Global APIs for Mobile Web

# Group Empty

## Empty [/pages/empty.json]
### Default [GET]
+ Response 200 (application/json)

        {
            "mat": {
                "startDate": "2014-11-27T17:52:25.125Z",
                "url": "api/mat.json",
                "code": "doTransfer",
                "action": "details",
                "appName": "SBA MOBILE",
                "appKey": "APP KEY",
                "appVersion": "0.14.1",
                "appCountry": "USA",
                "appPlatform": "android",
                "osVersion": "4.4",
                "userId": "id del usuario",
                "device": "Samsung Galaxy Nexus",
                "session": "sessionKey"
            },
            "user": {
                "wlBrand": "2"
            }
        }
        
## Empty with menu [/pages/empty/menu.json]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "backButton": {
                    "url": "index.html"
                }
            },
            "iwantto": [
                {
                    "text": "Hacer transferencia",
                    "type": "OPERATION",
                    "url": "transfers.html",
                    "eventId": null,
                    "jsId": null,
                    "params": null
                },
                {
                    "text": "Filtrar movimientos",
                    "type": "SEARCH",
                    "url": null,
                    "eventId": null,
                    "jsId": "js-filter-movements",
                    "params": null
                }
            ],
            "user": {
                "wlBrand": "3"
            }
        }

## Empty with menu without link [/pages/empty/menu-no-back.json]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "hideBackButton": true
            }
        }

        
# Group Language

## Load page [/pages/language.json]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": false,
                "hideBackButton": true
            },
            "pageContent": [
                {
                    "code": "en",
                    "name": "english",
                    "messageKey": "public.language.english",
                    "selected": true
                },
                {
                    "code": "es",
                    "name": "spanish",
                    "messageKey": "public.language.spanish",
                    "selected": false
                }
            ]
        }
        
## Service center page [/pages/language.json?mockId=1]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "backButton": {
                    "url": "index.html"
                }
            }
        }


# Group Index

## English index [/pages/index.json]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "hideBackButton": true
            },
            "alerts": [
                {
                    "type": "INFO",
                    "alert": [
                        {
                            "text": "Warning example",
                            "field": ""
                        }
                    ]
                }
            ],
            "crm": {
               "imageUrls": {
                    "def": "css/img/imageName.png",
                    "at2x": "css/img/imageName.@2x.png",
                    "hdpi": "css/img/imageName.hdpi.png",
                    "xhdpi": "css/img/imageName.xhdpi.png",
                    "xxhdpi": "css/img/imageName.xxhdpi.png"
                },
               "closeable": false,
               "location": "HOME"
            },
            "pageContent": {
                "feedback": "https://secure.opinionlab.com/ccc01/o.asp?id=CHAfLukV"
            }
        }

## Remembered user [/pages/index.json?mockId=2]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "hideBackButton": true
            },
            "pageContent": {
                "feedback": "https://secure.opinionlab.com/ccc01/o.asp?id=CHAfLukV",
                "remembered": true,
                "nickname": "Marcos Manuel",
                "lastSignonDate": "Wednesday 03/12/2014"
            }                
        }

## Message with link [/pages/index.json?mockId=3]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "hideBackButton": true
            },
            "alerts": [
                {
                    "type": "INFO",
                    "alert": [
                        {
                            "text": "No nearby points of interests found of the type.",
                            "field": "",
                            "link": {
                                "external": true,
                                "text": "Visit google",
                                "url": "https://www.google.com"
                            }
                        }
                    ]
                }
            ],
            "pageContent": {
                "feedback": "https://secure.opinionlab.com/ccc01/o.asp?id=CHAfLukV",
                "remembered": true,
                "nickname": "Marcos Manuel",
                "lastSignonDate": "Wednesday 03/12/2014"
            }                
        }
        
## White Label NBA [/pages/index.json?mockId=4]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "hideBackButton": true,
                "imageUrls": {
                    "def": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/HomeHeader4.png",
                    "at2x": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/HomeHeader4@2x.png",
                    "hdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/HomeHeader4.hdpi.png",
                    "xhdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/HomeHeader4.xhdpi.png",
                    "xxhdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/HomeHeader4.xxhdpi.png"
                }
            },
            "user": {
                "agent": {
                    "os": "Android"
                },
                "wlBrand": "4",
                "wlLogos": {
                    "def": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/Logo4.png",
                    "at2x": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/Logo4@2x.png",
                    "hdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/Logo4.hdpi.png",
                    "xhdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/Logo4.xhdpi.png",
                    "xxhdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/Logo4.xxhdpi.png"
                }
            },
            "alerts": [
                {
                    "type": "INFO",
                    "alert": [
                        {
                            "text": "Warning example",
                            "field": ""
                        }
                    ]
                }
            ],
            "crm": {
               "imageUrl" : "https://www.bbvacompass.com/offer/11000/img/",
               "closeable": false
            },
            "pageContent": {
                "feedback": "https://secure.opinionlab.com/ccc01/o.asp?id=CHAfLukV"
            }
        }

## White Label Clear Connect [/pages/index.json?mockId=5]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "hideBackButton": true
            },
            "user": {
                "wlBrand": "5"
            },
            "alerts": [
                {
                    "type": "INFO",
                    "alert": [
                        {
                            "text": "Warning example",
                            "field": ""
                        }
                    ]
                }
            ],
            "crm": {
               "imageUrl" : "https://www.bbvacompass.com/offer/11000/img/",
               "closeable": false
            },
            "pageContent": {
                "feedback": "https://secure.opinionlab.com/ccc01/o.asp?id=CHAfLukV"
            }
        }

## White Label Bama [/pages/index.json?mockId=6]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "hideBackButton": true,
                "imageUrls": {
                    "def": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/HomeHeader7.png",
                    "at2x": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/HomeHeader7@2x.png",
                    "hdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/HomeHeader7.hdpi.png",
                    "xhdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/HomeHeader7.xhdpi.png",
                    "xxhdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/HomeHeader7.xxhdpi.png"
                }
            },
            "user": {
                "agent": {
                    "os": "Android"
                },
                "wlBrand": "7",
                "wlLogos": {
                    "def": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/Logo7.png",
                    "at2x": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/Logo7@2x.png",
                    "hdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/Logo7.hdpi.png",
                    "xhdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/Logo7.xhdpi.png",
                    "xxhdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/Logo7.xxhdpi.png"
                }
            },
            "alerts": [
                {
                    "type": "INFO",
                    "alert": [
                        {
                            "text": "Warning example",
                            "field": ""
                        }
                    ]
                }
            ],
            "crm": {
               "imageUrl" : "https://www.bbvacompass.com/offer/11000/img/",
               "closeable": false
            },
            "pageContent": {
                "feedback": "https://secure.opinionlab.com/ccc01/o.asp?id=CHAfLukV"
            }
        }
        
## White Label Dynamo [/pages/index.json?mockId=7]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "hideBackButton": true,
                "imageUrls": {
                    "def": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/HomeHeader8.png",
                    "at2x": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/HomeHeader8@2x.png",
                    "hdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/HomeHeader8.hdpi.png",
                    "xhdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/HomeHeader8.xhdpi.png",
                    "xxhdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/HomeHeader8.xxhdpi.png"
                }
            },
            "user": {
                "agent": {
                    "os": "Android"
                },
                "wlBrand": "8",
                "wlLogos": {
                    "def": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/Logo8.png",
                    "at2x": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/Logo8@2x.png",
                    "hdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/Logo8.hdpi.png",
                    "xhdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/Logo8.xhdpi.png",
                    "xxhdpi": "https://www.bbvacompass.com/mobile-banking/redesign/whitelabel/Logo8.xxhdpi.png"
                }
            },
            "alerts": [
                {
                    "type": "INFO",
                    "alert": [
                        {
                            "text": "Warning example",
                            "field": ""
                        }
                    ]
                }
            ],
            "crm": {
               "imageUrl" : "https://www.bbvacompass.com/offer/11000/img/",
               "closeable": false
            },
            "pageContent": {
                "feedback": "https://secure.opinionlab.com/ccc01/o.asp?id=CHAfLukV"
            }
        }
        
## White Label NONE [/pages/index.json?mockId=8]
### Default [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "hideBackButton": true
            },
            "user": {
                "wlBrand": "2"
            },
            "alerts": [
                {
                    "type": "INFO",
                    "alert": [
                        {
                            "text": "Warning example",
                            "field": ""
                        }
                    ]
                }
            ],
            "crm": {
               "imageUrl" : "https://www.bbvacompass.com/offer/11000/img/",
               "closeable": false
            },
            "pageContent": {
                "feedback": "https://secure.opinionlab.com/ccc01/o.asp?id=CHAfLukV"
            }
        }


# Group Find us

## ATM & Branches [/api/findus/pois.json]
### Default [GET]

+ Request

        {
            "latitude": 33.52472222222222,
            "longitude": 86.81277777777778,
            "radius": null,
            "limit": null,
            "startAt": null
        }

+ Response 200 (application/json)

        {
            "alerts": null,
            "pageContent": [
                {
                    "type": "atm",
                    "idPoi": "atm_us_23_atm_us_bbva_atm",
                    "description": "BBVA ATM",
                    "latitude": 40.492765,
                    "longitude": -3.687185799999952,
                    "idBank": "9999",
                    "address1": "801 17th Staaa a N",
                    "address2": "Birmingham, AL 35203",
                    "distance": 60.950699987913,
                    "lobbyHours": {
                        "hours_mt":"24 hour - Yes"
                    }
                    
                },
                {
                    "type": "allPoint",
                    "idPoi": "allpoint_us_43_allpoint_us_bbva_allpoint",
                    "description": "All Point",
                    "latitude": 40.486009,
                    "longitude": -3.687052,
                    "idBank": "9999",
                    "address1": "801 17th St N",
                    "address2": "Birmingham, AL 35203",
                    "distance": 605.950699987913
                },
                {
                    "type": "branch",
                    "idPoi": "branch_us_12_branch_us_bbva_branch",
                    "description": "BBVA Branch",
                    "latitude": 40.480757,
                    "longitude": -3.68611,
                    "idBank": "9999",
                    "address1": "505 N 20th St, Suite 100",
                    "address2": "Birmingham, AL 35203",
                    "telephone": "(205) 297-3206",
                    "distance": 1609.044010287908,
                    "lobbyHours": {
                        "hours_mt":"24 hour - Yes",
                        "hours_fri":"24 hour - Yes",
                        "hours_sat":"24 hour - No"
                    },
                    "driveHours": {
                        "hours_mt":"12 hour - Yes",
                        "hours_fri":"12 hour - Yes",
                        "hours_sat":null
                    }
                    
                    
                },
                {
                    "type": "branch",
                    "idPoi": "branch_us_12_branch_us_bbva_branch",
                    "description": "BBVA Branch",
                    "latitude": 40.483757,
                    "longitude": -3.68111,
                    "idBank": "9999",
                    "address1": "505 N 20th St, Suite 100",
                    "address2": "Birmingham, AL 35203",
                    "telephone": "(205) 297-3206",
                    "distance": 1610.044010287908,
                    "lobbyHours": {
                        "hours_mt":"24 hour - Yes",
                        "hours_fri":"24 hour - Yes",
                        "hours_sat":"24 hour - No"
                    },
                    "driveHours": {
                        "hours_mt":"12 hour - Yes",
                        "hours_fri":"12 hour - Yes",
                        "hours_sat":null
                    }
                    
                    
                },
                {
                    "type": "branch",
                    "idPoi": "branch_us_22_branch_us_bbva_branch",
                    "description": "BBVA Branch",
                    "latitude": 40.487905,
                    "longitude": -3.694202,
                    "idBank": "9999",
                    "address1": "15 S 20th St",
                    "address2": "Birmingham, AL 35203",
                    "telephone": "(205) 297-1986",
                    "distance": 1900.044010287908,
                    "lobbyHours": {
                        "hours_mt":"24 hour - Yes",
                        "hours_fri":"24 hour - Yes",
                        "hours_sat":"24 hour - No"
                    },
                    "driveHours": {
                        "hours_mt":"12 hour - Yes",
                        "hours_fri":"12 hour - Yes",
                        "hours_sat":null
                    }
                }
            ]
            
        }


## Search address [/api/findus/address.json]
### Default [GET]

+ Request

        {
            "address": "Cardenal Herrera Oria"
        }

+ Response 200 (application/json)

        {
            "alerts": null,
            "pageContent": [
                {
                    "latitude": 40.48214,
                    "longitude": -3.718589,
                    "address1": "Avenida Cardenal Herrera Oria, Madrid, España"
                },
                {
                    "latitude": 36.840657,
                    "longitude": -2.455252,
                    "address1": "Calle Cardenal Herrera Oria, Almeria, España"
                },
                {
                    "latitude": 43.455987,
                    "longitude": -3.851849,
                    "address1": "Avenida Cardenal Herrera Oria, Santander, España"
                },
                {
                    "latitude": 43.458694,
                    "longitude": -3.841492,
                    "address1": "Calle Cardenal Herrera Oria, Santander, España"
                },
                {
                    "latitude": 36.428944,
                    "longitude": -5.14776,
                    "address1": "Calle Cardenal Herrera Oria, 29680 Estepona, Málaga, España"
                }
            ]
        }


## Search address with empty result [/api/findus/address.json?mockId=2]
### Default [GET]

+ Request

        {
            "address": "Euclideaaa"
        }

+ Response 200 (application/json)

        {
            "alerts": [
                {
                    "type": "INFO",
                    "alert": [
                        {
                            "text": "No nearby points of interests found of the type.",
                            "field": ""
                        }
                    ]
                }
            ],
            "pageContent": []
        }


# Group Warnings


## Warnings [/pages/warnings.json]
### Default [GET]
+ Response 200 (application/json)

        { 
            "text": "Mobile and Online Banking will be unavailable Sat 11/23 from 12AM to 3AM CT",
            "url":"",
            "active":"N"
        }



# Group Error

Global error view

## Error with custom messages [/pages/error.json]
### Custom error [GET]
+ Response 200 (application/json)

        {
            "error": {
                "errorMsg": "Some error happened while performing operation"
            }
        }

## Error without custom messages [/pages/error.json?mockId=2]
### Custom error [GET]
+ Response 200 (application/json)

        {
            
        }
        

# Group I Want To

I Want To Button example

## I Want To [/components/iwantto.json]
### Custom error [GET]
+ Response 200 (application/json)

        {
            "iwantto": [
                {
                    "text": "Hacer transferencia",
                    "type": "OPERATION",
                    "url": "transfers.html",
                    "eventId": null,
                    "jsId": null,
                    "params": null
                },
                {
                    "text": "Filtrar movimientos",
                    "type": "SEARCH",
                    "url": null,
                    "eventId": null,
                    "jsId": "js-filter-movements",
                    "params": null
                }
            ]
        }


# Group New Features

Example of new features

## Examples of spanish Web [/pages/newFeatures.json]
### Valid response [GET]
+ Response 200 (application/json)

        {
            "pageContent": [
                {
                    "title": "Automatic access",
                    "image": {
                        "alt": "Automatic access",
                        "url": "http://dev-bbva-buzz.appspot.com/dist_0.1.0/images/release/acceso.png"
                    },
                    "text": "Access the application directly without needing to enter your password. Register for the Automatic Access service, which you can access from \"Menu - Settings\" and enter quickly and securely."
                },
                {
                    "title": "\"About\" on side menu",
                    "image": {
                        "alt": "\"About\" on side menu",
                        "url": "http://dev-bbva-buzz.appspot.com/dist_0.1.0/images/release/acceso.png"
                    },
                    "text": "We have created a section for you in which you can view the application's new features, report errors and rate the application, as well as following BBVA breaking news on social networks."
                },
                {
                    "title": "Payment of bills that are not direct debited",
                    "image": {
                        "alt": "Payment of bills that are not direct debited",
                        "url": "http://dev-bbva-buzz.appspot.com/dist_0.1.0/images/release/rnd.png"
                    },
                    "text": "You can now pay your bills and taxes that are not direct debited from your cell phone, by taking a photo of the barcode with your camera. Go to the \"Non-direct debited payments\" on the Menu and select the option that best matches your preferences."
                },        
                {
                    "title": "See card CVV",
                    "image": {
                        "alt": "See card CVV",
                        "url": "http://dev-bbva-buzz.appspot.com/dist_0.1.0/images/release/alta.png"
                    },
                    "text": "Now you can view the CVV of any of your cards from the BBVA mobile application. Click on the image of your card that is displayed at the top."
                },        
                {
                    "title": "Activate card",
                    "image": {
                        "alt": "Activate card",
                        "url": "http://dev-bbva-buzz.appspot.com/dist_0.1.0/images/release/adjuntos.png"
                    },
                    "text": "Use your new cards right away. You can activate them from \"I want\" on the Menu."
                },        
                {
                    "title": "Copy account IBAN number",
                    "image": {
                        "alt": "Copy account IBAN number",
                        "url": "http://dev-bbva-buzz.appspot.com/dist_0.1.0/images/release/rnd.png"
                    },
                    "text": "Share your account number easily. To copy the IBAN, just click on the account icon at the top of the detailed transactions. You can also do it from \"I want - More information\"."
                },        
                {
                    "title": "Copy card PAN",
                    "image": {
                        "alt": "Copy card PAN",
                        "url": "http://dev-bbva-buzz.appspot.com/dist_0.1.0/images/release/adjuntos.png"
                    },
                    "text": "Save time with your Internet purchases by copying your card number (PAN). You will do it from \"I want - More information\" for any of them."
                },        
                {
                    "title": "Repeat transfer",
                    "image": {
                        "alt": "Repeat transfer",
                        "url": "http://dev-bbva-buzz.appspot.com/dist_0.1.0/images/release/acceso.png"
                    },
                    "text": "Access the details about a transfer and you can easily repeat the transaction, with the details already loaded and the option to modify them."
                }
            ]
        }

## CRM Offer [/pages/crm/offer.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "header": {
              "showMenu": true
            },
            "pageContent": {
                "url": "/crm/tmpIframeCrm.html",
                "location": "DASHBOARD"
            }
        }

## Video Container [/pages/iframeModalContainer.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "header": {
              "title": "Video"
            },
            "pageContent" : "https://player.vimeo.com/video/90150975"
        }


## List of holidays [/api/holidays.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "status": "OK",
            "pageContent": [
                "2012-01-02",
                "2012-01-16",
                "2012-02-20",
                "2012-05-28",
                "2012-07-04",
                "2012-09-03",
                "2012-10-08",
                "2012-11-12",
                "2012-11-22",
                "2012-12-25",
                "2013-01-01",
                "2013-01-21",
                "2013-02-18",
                "2013-05-27",
                "2013-07-04",
                "2013-09-02",
                "2013-10-14",
                "2013-11-11",
                "2013-11-28",
                "2013-12-25",
                "2014-01-01",
                "2014-01-20",
                "2014-02-17",
                "2014-05-26",
                "2014-07-04",
                "2014-09-01",
                "2014-10-13",
                "2014-11-11",
                "2014-11-27",
                "2014-12-25"
            ]
        }
        
## Mat [/api/mat.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "status": "OK",
            "pageContent": {
            }
        }
        
## Load [/load/init.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "uid": "userUid"
        }
